# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/eoserv/Desktop/eoserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/eoserv/Desktop/eoserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eoserv/Desktop/eoserv/CMakeFiles /home/eoserv/Desktop/eoserv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/eoserv/Desktop/eoserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eoserv

# Build rule for target.
eoserv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eoserv
.PHONY : eoserv

# fast build rule for target.
eoserv/fast:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/build
.PHONY : eoserv/fast

src/arena.o: src/arena.cpp.o

.PHONY : src/arena.o

# target to build an object file
src/arena.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/arena.cpp.o
.PHONY : src/arena.cpp.o

src/arena.i: src/arena.cpp.i

.PHONY : src/arena.i

# target to preprocess a source file
src/arena.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/arena.cpp.i
.PHONY : src/arena.cpp.i

src/arena.s: src/arena.cpp.s

.PHONY : src/arena.s

# target to generate assembly for a file
src/arena.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/arena.cpp.s
.PHONY : src/arena.cpp.s

src/character.o: src/character.cpp.o

.PHONY : src/character.o

# target to build an object file
src/character.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/character.cpp.o
.PHONY : src/character.cpp.o

src/character.i: src/character.cpp.i

.PHONY : src/character.i

# target to preprocess a source file
src/character.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/character.cpp.i
.PHONY : src/character.cpp.i

src/character.s: src/character.cpp.s

.PHONY : src/character.s

# target to generate assembly for a file
src/character.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/character.cpp.s
.PHONY : src/character.cpp.s

src/command_source.o: src/command_source.cpp.o

.PHONY : src/command_source.o

# target to build an object file
src/command_source.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/command_source.cpp.o
.PHONY : src/command_source.cpp.o

src/command_source.i: src/command_source.cpp.i

.PHONY : src/command_source.i

# target to preprocess a source file
src/command_source.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/command_source.cpp.i
.PHONY : src/command_source.cpp.i

src/command_source.s: src/command_source.cpp.s

.PHONY : src/command_source.s

# target to generate assembly for a file
src/command_source.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/command_source.cpp.s
.PHONY : src/command_source.cpp.s

src/commands/admin.o: src/commands/admin.cpp.o

.PHONY : src/commands/admin.o

# target to build an object file
src/commands/admin.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/admin.cpp.o
.PHONY : src/commands/admin.cpp.o

src/commands/admin.i: src/commands/admin.cpp.i

.PHONY : src/commands/admin.i

# target to preprocess a source file
src/commands/admin.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/admin.cpp.i
.PHONY : src/commands/admin.cpp.i

src/commands/admin.s: src/commands/admin.cpp.s

.PHONY : src/commands/admin.s

# target to generate assembly for a file
src/commands/admin.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/admin.cpp.s
.PHONY : src/commands/admin.cpp.s

src/commands/char_mod.o: src/commands/char_mod.cpp.o

.PHONY : src/commands/char_mod.o

# target to build an object file
src/commands/char_mod.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/char_mod.cpp.o
.PHONY : src/commands/char_mod.cpp.o

src/commands/char_mod.i: src/commands/char_mod.cpp.i

.PHONY : src/commands/char_mod.i

# target to preprocess a source file
src/commands/char_mod.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/char_mod.cpp.i
.PHONY : src/commands/char_mod.cpp.i

src/commands/char_mod.s: src/commands/char_mod.cpp.s

.PHONY : src/commands/char_mod.s

# target to generate assembly for a file
src/commands/char_mod.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/char_mod.cpp.s
.PHONY : src/commands/char_mod.cpp.s

src/commands/commands.o: src/commands/commands.cpp.o

.PHONY : src/commands/commands.o

# target to build an object file
src/commands/commands.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/commands.cpp.o
.PHONY : src/commands/commands.cpp.o

src/commands/commands.i: src/commands/commands.cpp.i

.PHONY : src/commands/commands.i

# target to preprocess a source file
src/commands/commands.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/commands.cpp.i
.PHONY : src/commands/commands.cpp.i

src/commands/commands.s: src/commands/commands.cpp.s

.PHONY : src/commands/commands.s

# target to generate assembly for a file
src/commands/commands.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/commands.cpp.s
.PHONY : src/commands/commands.cpp.s

src/commands/debug.o: src/commands/debug.cpp.o

.PHONY : src/commands/debug.o

# target to build an object file
src/commands/debug.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/debug.cpp.o
.PHONY : src/commands/debug.cpp.o

src/commands/debug.i: src/commands/debug.cpp.i

.PHONY : src/commands/debug.i

# target to preprocess a source file
src/commands/debug.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/debug.cpp.i
.PHONY : src/commands/debug.cpp.i

src/commands/debug.s: src/commands/debug.cpp.s

.PHONY : src/commands/debug.s

# target to generate assembly for a file
src/commands/debug.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/debug.cpp.s
.PHONY : src/commands/debug.cpp.s

src/commands/general.o: src/commands/general.cpp.o

.PHONY : src/commands/general.o

# target to build an object file
src/commands/general.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/general.cpp.o
.PHONY : src/commands/general.cpp.o

src/commands/general.i: src/commands/general.cpp.i

.PHONY : src/commands/general.i

# target to preprocess a source file
src/commands/general.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/general.cpp.i
.PHONY : src/commands/general.cpp.i

src/commands/general.s: src/commands/general.cpp.s

.PHONY : src/commands/general.s

# target to generate assembly for a file
src/commands/general.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/general.cpp.s
.PHONY : src/commands/general.cpp.s

src/commands/info.o: src/commands/info.cpp.o

.PHONY : src/commands/info.o

# target to build an object file
src/commands/info.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/info.cpp.o
.PHONY : src/commands/info.cpp.o

src/commands/info.i: src/commands/info.cpp.i

.PHONY : src/commands/info.i

# target to preprocess a source file
src/commands/info.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/info.cpp.i
.PHONY : src/commands/info.cpp.i

src/commands/info.s: src/commands/info.cpp.s

.PHONY : src/commands/info.s

# target to generate assembly for a file
src/commands/info.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/info.cpp.s
.PHONY : src/commands/info.cpp.s

src/commands/map.o: src/commands/map.cpp.o

.PHONY : src/commands/map.o

# target to build an object file
src/commands/map.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/map.cpp.o
.PHONY : src/commands/map.cpp.o

src/commands/map.i: src/commands/map.cpp.i

.PHONY : src/commands/map.i

# target to preprocess a source file
src/commands/map.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/map.cpp.i
.PHONY : src/commands/map.cpp.i

src/commands/map.s: src/commands/map.cpp.s

.PHONY : src/commands/map.s

# target to generate assembly for a file
src/commands/map.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/map.cpp.s
.PHONY : src/commands/map.cpp.s

src/commands/moderation.o: src/commands/moderation.cpp.o

.PHONY : src/commands/moderation.o

# target to build an object file
src/commands/moderation.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/moderation.cpp.o
.PHONY : src/commands/moderation.cpp.o

src/commands/moderation.i: src/commands/moderation.cpp.i

.PHONY : src/commands/moderation.i

# target to preprocess a source file
src/commands/moderation.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/moderation.cpp.i
.PHONY : src/commands/moderation.cpp.i

src/commands/moderation.s: src/commands/moderation.cpp.s

.PHONY : src/commands/moderation.s

# target to generate assembly for a file
src/commands/moderation.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/moderation.cpp.s
.PHONY : src/commands/moderation.cpp.s

src/commands/player.o: src/commands/player.cpp.o

.PHONY : src/commands/player.o

# target to build an object file
src/commands/player.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/player.cpp.o
.PHONY : src/commands/player.cpp.o

src/commands/player.i: src/commands/player.cpp.i

.PHONY : src/commands/player.i

# target to preprocess a source file
src/commands/player.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/player.cpp.i
.PHONY : src/commands/player.cpp.i

src/commands/player.s: src/commands/player.cpp.s

.PHONY : src/commands/player.s

# target to generate assembly for a file
src/commands/player.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/player.cpp.s
.PHONY : src/commands/player.cpp.s

src/commands/server.o: src/commands/server.cpp.o

.PHONY : src/commands/server.o

# target to build an object file
src/commands/server.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/server.cpp.o
.PHONY : src/commands/server.cpp.o

src/commands/server.i: src/commands/server.cpp.i

.PHONY : src/commands/server.i

# target to preprocess a source file
src/commands/server.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/server.cpp.i
.PHONY : src/commands/server.cpp.i

src/commands/server.s: src/commands/server.cpp.s

.PHONY : src/commands/server.s

# target to generate assembly for a file
src/commands/server.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/server.cpp.s
.PHONY : src/commands/server.cpp.s

src/commands/warp.o: src/commands/warp.cpp.o

.PHONY : src/commands/warp.o

# target to build an object file
src/commands/warp.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/warp.cpp.o
.PHONY : src/commands/warp.cpp.o

src/commands/warp.i: src/commands/warp.cpp.i

.PHONY : src/commands/warp.i

# target to preprocess a source file
src/commands/warp.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/warp.cpp.i
.PHONY : src/commands/warp.cpp.i

src/commands/warp.s: src/commands/warp.cpp.s

.PHONY : src/commands/warp.s

# target to generate assembly for a file
src/commands/warp.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/commands/warp.cpp.s
.PHONY : src/commands/warp.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/console.o: src/console.cpp.o

.PHONY : src/console.o

# target to build an object file
src/console.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/console.cpp.o
.PHONY : src/console.cpp.o

src/console.i: src/console.cpp.i

.PHONY : src/console.i

# target to preprocess a source file
src/console.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/console.cpp.i
.PHONY : src/console.cpp.i

src/console.s: src/console.cpp.s

.PHONY : src/console.s

# target to generate assembly for a file
src/console.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/console.cpp.s
.PHONY : src/console.cpp.s

src/database.o: src/database.cpp.o

.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i

.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s

.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/dialog.o: src/dialog.cpp.o

.PHONY : src/dialog.o

# target to build an object file
src/dialog.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/dialog.cpp.o
.PHONY : src/dialog.cpp.o

src/dialog.i: src/dialog.cpp.i

.PHONY : src/dialog.i

# target to preprocess a source file
src/dialog.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/dialog.cpp.i
.PHONY : src/dialog.cpp.i

src/dialog.s: src/dialog.cpp.s

.PHONY : src/dialog.s

# target to generate assembly for a file
src/dialog.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/dialog.cpp.s
.PHONY : src/dialog.cpp.s

src/eoclient.o: src/eoclient.cpp.o

.PHONY : src/eoclient.o

# target to build an object file
src/eoclient.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoclient.cpp.o
.PHONY : src/eoclient.cpp.o

src/eoclient.i: src/eoclient.cpp.i

.PHONY : src/eoclient.i

# target to preprocess a source file
src/eoclient.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoclient.cpp.i
.PHONY : src/eoclient.cpp.i

src/eoclient.s: src/eoclient.cpp.s

.PHONY : src/eoclient.s

# target to generate assembly for a file
src/eoclient.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoclient.cpp.s
.PHONY : src/eoclient.cpp.s

src/eodata.o: src/eodata.cpp.o

.PHONY : src/eodata.o

# target to build an object file
src/eodata.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eodata.cpp.o
.PHONY : src/eodata.cpp.o

src/eodata.i: src/eodata.cpp.i

.PHONY : src/eodata.i

# target to preprocess a source file
src/eodata.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eodata.cpp.i
.PHONY : src/eodata.cpp.i

src/eodata.s: src/eodata.cpp.s

.PHONY : src/eodata.s

# target to generate assembly for a file
src/eodata.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eodata.cpp.s
.PHONY : src/eodata.cpp.s

src/eoplus.o: src/eoplus.cpp.o

.PHONY : src/eoplus.o

# target to build an object file
src/eoplus.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus.cpp.o
.PHONY : src/eoplus.cpp.o

src/eoplus.i: src/eoplus.cpp.i

.PHONY : src/eoplus.i

# target to preprocess a source file
src/eoplus.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus.cpp.i
.PHONY : src/eoplus.cpp.i

src/eoplus.s: src/eoplus.cpp.s

.PHONY : src/eoplus.s

# target to generate assembly for a file
src/eoplus.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus.cpp.s
.PHONY : src/eoplus.cpp.s

src/eoplus/context.o: src/eoplus/context.cpp.o

.PHONY : src/eoplus/context.o

# target to build an object file
src/eoplus/context.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/context.cpp.o
.PHONY : src/eoplus/context.cpp.o

src/eoplus/context.i: src/eoplus/context.cpp.i

.PHONY : src/eoplus/context.i

# target to preprocess a source file
src/eoplus/context.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/context.cpp.i
.PHONY : src/eoplus/context.cpp.i

src/eoplus/context.s: src/eoplus/context.cpp.s

.PHONY : src/eoplus/context.s

# target to generate assembly for a file
src/eoplus/context.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/context.cpp.s
.PHONY : src/eoplus/context.cpp.s

src/eoplus/lex.o: src/eoplus/lex.cpp.o

.PHONY : src/eoplus/lex.o

# target to build an object file
src/eoplus/lex.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/lex.cpp.o
.PHONY : src/eoplus/lex.cpp.o

src/eoplus/lex.i: src/eoplus/lex.cpp.i

.PHONY : src/eoplus/lex.i

# target to preprocess a source file
src/eoplus/lex.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/lex.cpp.i
.PHONY : src/eoplus/lex.cpp.i

src/eoplus/lex.s: src/eoplus/lex.cpp.s

.PHONY : src/eoplus/lex.s

# target to generate assembly for a file
src/eoplus/lex.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/lex.cpp.s
.PHONY : src/eoplus/lex.cpp.s

src/eoplus/parse.o: src/eoplus/parse.cpp.o

.PHONY : src/eoplus/parse.o

# target to build an object file
src/eoplus/parse.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/parse.cpp.o
.PHONY : src/eoplus/parse.cpp.o

src/eoplus/parse.i: src/eoplus/parse.cpp.i

.PHONY : src/eoplus/parse.i

# target to preprocess a source file
src/eoplus/parse.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/parse.cpp.i
.PHONY : src/eoplus/parse.cpp.i

src/eoplus/parse.s: src/eoplus/parse.cpp.s

.PHONY : src/eoplus/parse.s

# target to generate assembly for a file
src/eoplus/parse.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoplus/parse.cpp.s
.PHONY : src/eoplus/parse.cpp.s

src/eoserv_config.o: src/eoserv_config.cpp.o

.PHONY : src/eoserv_config.o

# target to build an object file
src/eoserv_config.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoserv_config.cpp.o
.PHONY : src/eoserv_config.cpp.o

src/eoserv_config.i: src/eoserv_config.cpp.i

.PHONY : src/eoserv_config.i

# target to preprocess a source file
src/eoserv_config.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoserv_config.cpp.i
.PHONY : src/eoserv_config.cpp.i

src/eoserv_config.s: src/eoserv_config.cpp.s

.PHONY : src/eoserv_config.s

# target to generate assembly for a file
src/eoserv_config.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoserv_config.cpp.s
.PHONY : src/eoserv_config.cpp.s

src/eoserver.o: src/eoserver.cpp.o

.PHONY : src/eoserver.o

# target to build an object file
src/eoserver.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoserver.cpp.o
.PHONY : src/eoserver.cpp.o

src/eoserver.i: src/eoserver.cpp.i

.PHONY : src/eoserver.i

# target to preprocess a source file
src/eoserver.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoserver.cpp.i
.PHONY : src/eoserver.cpp.i

src/eoserver.s: src/eoserver.cpp.s

.PHONY : src/eoserver.s

# target to generate assembly for a file
src/eoserver.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/eoserver.cpp.s
.PHONY : src/eoserver.cpp.s

src/extra/seose_compat.o: src/extra/seose_compat.cpp.o

.PHONY : src/extra/seose_compat.o

# target to build an object file
src/extra/seose_compat.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/extra/seose_compat.cpp.o
.PHONY : src/extra/seose_compat.cpp.o

src/extra/seose_compat.i: src/extra/seose_compat.cpp.i

.PHONY : src/extra/seose_compat.i

# target to preprocess a source file
src/extra/seose_compat.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/extra/seose_compat.cpp.i
.PHONY : src/extra/seose_compat.cpp.i

src/extra/seose_compat.s: src/extra/seose_compat.cpp.s

.PHONY : src/extra/seose_compat.s

# target to generate assembly for a file
src/extra/seose_compat.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/extra/seose_compat.cpp.s
.PHONY : src/extra/seose_compat.cpp.s

src/guild.o: src/guild.cpp.o

.PHONY : src/guild.o

# target to build an object file
src/guild.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/guild.cpp.o
.PHONY : src/guild.cpp.o

src/guild.i: src/guild.cpp.i

.PHONY : src/guild.i

# target to preprocess a source file
src/guild.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/guild.cpp.i
.PHONY : src/guild.cpp.i

src/guild.s: src/guild.cpp.s

.PHONY : src/guild.s

# target to generate assembly for a file
src/guild.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/guild.cpp.s
.PHONY : src/guild.cpp.s

src/handlers/Account.o: src/handlers/Account.cpp.o

.PHONY : src/handlers/Account.o

# target to build an object file
src/handlers/Account.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Account.cpp.o
.PHONY : src/handlers/Account.cpp.o

src/handlers/Account.i: src/handlers/Account.cpp.i

.PHONY : src/handlers/Account.i

# target to preprocess a source file
src/handlers/Account.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Account.cpp.i
.PHONY : src/handlers/Account.cpp.i

src/handlers/Account.s: src/handlers/Account.cpp.s

.PHONY : src/handlers/Account.s

# target to generate assembly for a file
src/handlers/Account.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Account.cpp.s
.PHONY : src/handlers/Account.cpp.s

src/handlers/AdminInteract.o: src/handlers/AdminInteract.cpp.o

.PHONY : src/handlers/AdminInteract.o

# target to build an object file
src/handlers/AdminInteract.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/AdminInteract.cpp.o
.PHONY : src/handlers/AdminInteract.cpp.o

src/handlers/AdminInteract.i: src/handlers/AdminInteract.cpp.i

.PHONY : src/handlers/AdminInteract.i

# target to preprocess a source file
src/handlers/AdminInteract.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/AdminInteract.cpp.i
.PHONY : src/handlers/AdminInteract.cpp.i

src/handlers/AdminInteract.s: src/handlers/AdminInteract.cpp.s

.PHONY : src/handlers/AdminInteract.s

# target to generate assembly for a file
src/handlers/AdminInteract.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/AdminInteract.cpp.s
.PHONY : src/handlers/AdminInteract.cpp.s

src/handlers/Attack.o: src/handlers/Attack.cpp.o

.PHONY : src/handlers/Attack.o

# target to build an object file
src/handlers/Attack.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Attack.cpp.o
.PHONY : src/handlers/Attack.cpp.o

src/handlers/Attack.i: src/handlers/Attack.cpp.i

.PHONY : src/handlers/Attack.i

# target to preprocess a source file
src/handlers/Attack.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Attack.cpp.i
.PHONY : src/handlers/Attack.cpp.i

src/handlers/Attack.s: src/handlers/Attack.cpp.s

.PHONY : src/handlers/Attack.s

# target to generate assembly for a file
src/handlers/Attack.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Attack.cpp.s
.PHONY : src/handlers/Attack.cpp.s

src/handlers/Bank.o: src/handlers/Bank.cpp.o

.PHONY : src/handlers/Bank.o

# target to build an object file
src/handlers/Bank.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Bank.cpp.o
.PHONY : src/handlers/Bank.cpp.o

src/handlers/Bank.i: src/handlers/Bank.cpp.i

.PHONY : src/handlers/Bank.i

# target to preprocess a source file
src/handlers/Bank.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Bank.cpp.i
.PHONY : src/handlers/Bank.cpp.i

src/handlers/Bank.s: src/handlers/Bank.cpp.s

.PHONY : src/handlers/Bank.s

# target to generate assembly for a file
src/handlers/Bank.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Bank.cpp.s
.PHONY : src/handlers/Bank.cpp.s

src/handlers/Barber.o: src/handlers/Barber.cpp.o

.PHONY : src/handlers/Barber.o

# target to build an object file
src/handlers/Barber.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Barber.cpp.o
.PHONY : src/handlers/Barber.cpp.o

src/handlers/Barber.i: src/handlers/Barber.cpp.i

.PHONY : src/handlers/Barber.i

# target to preprocess a source file
src/handlers/Barber.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Barber.cpp.i
.PHONY : src/handlers/Barber.cpp.i

src/handlers/Barber.s: src/handlers/Barber.cpp.s

.PHONY : src/handlers/Barber.s

# target to generate assembly for a file
src/handlers/Barber.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Barber.cpp.s
.PHONY : src/handlers/Barber.cpp.s

src/handlers/Board.o: src/handlers/Board.cpp.o

.PHONY : src/handlers/Board.o

# target to build an object file
src/handlers/Board.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Board.cpp.o
.PHONY : src/handlers/Board.cpp.o

src/handlers/Board.i: src/handlers/Board.cpp.i

.PHONY : src/handlers/Board.i

# target to preprocess a source file
src/handlers/Board.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Board.cpp.i
.PHONY : src/handlers/Board.cpp.i

src/handlers/Board.s: src/handlers/Board.cpp.s

.PHONY : src/handlers/Board.s

# target to generate assembly for a file
src/handlers/Board.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Board.cpp.s
.PHONY : src/handlers/Board.cpp.s

src/handlers/Book.o: src/handlers/Book.cpp.o

.PHONY : src/handlers/Book.o

# target to build an object file
src/handlers/Book.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Book.cpp.o
.PHONY : src/handlers/Book.cpp.o

src/handlers/Book.i: src/handlers/Book.cpp.i

.PHONY : src/handlers/Book.i

# target to preprocess a source file
src/handlers/Book.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Book.cpp.i
.PHONY : src/handlers/Book.cpp.i

src/handlers/Book.s: src/handlers/Book.cpp.s

.PHONY : src/handlers/Book.s

# target to generate assembly for a file
src/handlers/Book.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Book.cpp.s
.PHONY : src/handlers/Book.cpp.s

src/handlers/Chair.o: src/handlers/Chair.cpp.o

.PHONY : src/handlers/Chair.o

# target to build an object file
src/handlers/Chair.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Chair.cpp.o
.PHONY : src/handlers/Chair.cpp.o

src/handlers/Chair.i: src/handlers/Chair.cpp.i

.PHONY : src/handlers/Chair.i

# target to preprocess a source file
src/handlers/Chair.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Chair.cpp.i
.PHONY : src/handlers/Chair.cpp.i

src/handlers/Chair.s: src/handlers/Chair.cpp.s

.PHONY : src/handlers/Chair.s

# target to generate assembly for a file
src/handlers/Chair.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Chair.cpp.s
.PHONY : src/handlers/Chair.cpp.s

src/handlers/Character.o: src/handlers/Character.cpp.o

.PHONY : src/handlers/Character.o

# target to build an object file
src/handlers/Character.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Character.cpp.o
.PHONY : src/handlers/Character.cpp.o

src/handlers/Character.i: src/handlers/Character.cpp.i

.PHONY : src/handlers/Character.i

# target to preprocess a source file
src/handlers/Character.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Character.cpp.i
.PHONY : src/handlers/Character.cpp.i

src/handlers/Character.s: src/handlers/Character.cpp.s

.PHONY : src/handlers/Character.s

# target to generate assembly for a file
src/handlers/Character.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Character.cpp.s
.PHONY : src/handlers/Character.cpp.s

src/handlers/Chest.o: src/handlers/Chest.cpp.o

.PHONY : src/handlers/Chest.o

# target to build an object file
src/handlers/Chest.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Chest.cpp.o
.PHONY : src/handlers/Chest.cpp.o

src/handlers/Chest.i: src/handlers/Chest.cpp.i

.PHONY : src/handlers/Chest.i

# target to preprocess a source file
src/handlers/Chest.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Chest.cpp.i
.PHONY : src/handlers/Chest.cpp.i

src/handlers/Chest.s: src/handlers/Chest.cpp.s

.PHONY : src/handlers/Chest.s

# target to generate assembly for a file
src/handlers/Chest.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Chest.cpp.s
.PHONY : src/handlers/Chest.cpp.s

src/handlers/Citizen.o: src/handlers/Citizen.cpp.o

.PHONY : src/handlers/Citizen.o

# target to build an object file
src/handlers/Citizen.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Citizen.cpp.o
.PHONY : src/handlers/Citizen.cpp.o

src/handlers/Citizen.i: src/handlers/Citizen.cpp.i

.PHONY : src/handlers/Citizen.i

# target to preprocess a source file
src/handlers/Citizen.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Citizen.cpp.i
.PHONY : src/handlers/Citizen.cpp.i

src/handlers/Citizen.s: src/handlers/Citizen.cpp.s

.PHONY : src/handlers/Citizen.s

# target to generate assembly for a file
src/handlers/Citizen.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Citizen.cpp.s
.PHONY : src/handlers/Citizen.cpp.s

src/handlers/Connection.o: src/handlers/Connection.cpp.o

.PHONY : src/handlers/Connection.o

# target to build an object file
src/handlers/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Connection.cpp.o
.PHONY : src/handlers/Connection.cpp.o

src/handlers/Connection.i: src/handlers/Connection.cpp.i

.PHONY : src/handlers/Connection.i

# target to preprocess a source file
src/handlers/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Connection.cpp.i
.PHONY : src/handlers/Connection.cpp.i

src/handlers/Connection.s: src/handlers/Connection.cpp.s

.PHONY : src/handlers/Connection.s

# target to generate assembly for a file
src/handlers/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Connection.cpp.s
.PHONY : src/handlers/Connection.cpp.s

src/handlers/Door.o: src/handlers/Door.cpp.o

.PHONY : src/handlers/Door.o

# target to build an object file
src/handlers/Door.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Door.cpp.o
.PHONY : src/handlers/Door.cpp.o

src/handlers/Door.i: src/handlers/Door.cpp.i

.PHONY : src/handlers/Door.i

# target to preprocess a source file
src/handlers/Door.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Door.cpp.i
.PHONY : src/handlers/Door.cpp.i

src/handlers/Door.s: src/handlers/Door.cpp.s

.PHONY : src/handlers/Door.s

# target to generate assembly for a file
src/handlers/Door.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Door.cpp.s
.PHONY : src/handlers/Door.cpp.s

src/handlers/Emote.o: src/handlers/Emote.cpp.o

.PHONY : src/handlers/Emote.o

# target to build an object file
src/handlers/Emote.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Emote.cpp.o
.PHONY : src/handlers/Emote.cpp.o

src/handlers/Emote.i: src/handlers/Emote.cpp.i

.PHONY : src/handlers/Emote.i

# target to preprocess a source file
src/handlers/Emote.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Emote.cpp.i
.PHONY : src/handlers/Emote.cpp.i

src/handlers/Emote.s: src/handlers/Emote.cpp.s

.PHONY : src/handlers/Emote.s

# target to generate assembly for a file
src/handlers/Emote.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Emote.cpp.s
.PHONY : src/handlers/Emote.cpp.s

src/handlers/Face.o: src/handlers/Face.cpp.o

.PHONY : src/handlers/Face.o

# target to build an object file
src/handlers/Face.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Face.cpp.o
.PHONY : src/handlers/Face.cpp.o

src/handlers/Face.i: src/handlers/Face.cpp.i

.PHONY : src/handlers/Face.i

# target to preprocess a source file
src/handlers/Face.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Face.cpp.i
.PHONY : src/handlers/Face.cpp.i

src/handlers/Face.s: src/handlers/Face.cpp.s

.PHONY : src/handlers/Face.s

# target to generate assembly for a file
src/handlers/Face.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Face.cpp.s
.PHONY : src/handlers/Face.cpp.s

src/handlers/Global.o: src/handlers/Global.cpp.o

.PHONY : src/handlers/Global.o

# target to build an object file
src/handlers/Global.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Global.cpp.o
.PHONY : src/handlers/Global.cpp.o

src/handlers/Global.i: src/handlers/Global.cpp.i

.PHONY : src/handlers/Global.i

# target to preprocess a source file
src/handlers/Global.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Global.cpp.i
.PHONY : src/handlers/Global.cpp.i

src/handlers/Global.s: src/handlers/Global.cpp.s

.PHONY : src/handlers/Global.s

# target to generate assembly for a file
src/handlers/Global.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Global.cpp.s
.PHONY : src/handlers/Global.cpp.s

src/handlers/Guild.o: src/handlers/Guild.cpp.o

.PHONY : src/handlers/Guild.o

# target to build an object file
src/handlers/Guild.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Guild.cpp.o
.PHONY : src/handlers/Guild.cpp.o

src/handlers/Guild.i: src/handlers/Guild.cpp.i

.PHONY : src/handlers/Guild.i

# target to preprocess a source file
src/handlers/Guild.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Guild.cpp.i
.PHONY : src/handlers/Guild.cpp.i

src/handlers/Guild.s: src/handlers/Guild.cpp.s

.PHONY : src/handlers/Guild.s

# target to generate assembly for a file
src/handlers/Guild.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Guild.cpp.s
.PHONY : src/handlers/Guild.cpp.s

src/handlers/Init.o: src/handlers/Init.cpp.o

.PHONY : src/handlers/Init.o

# target to build an object file
src/handlers/Init.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Init.cpp.o
.PHONY : src/handlers/Init.cpp.o

src/handlers/Init.i: src/handlers/Init.cpp.i

.PHONY : src/handlers/Init.i

# target to preprocess a source file
src/handlers/Init.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Init.cpp.i
.PHONY : src/handlers/Init.cpp.i

src/handlers/Init.s: src/handlers/Init.cpp.s

.PHONY : src/handlers/Init.s

# target to generate assembly for a file
src/handlers/Init.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Init.cpp.s
.PHONY : src/handlers/Init.cpp.s

src/handlers/Internal.o: src/handlers/Internal.cpp.o

.PHONY : src/handlers/Internal.o

# target to build an object file
src/handlers/Internal.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Internal.cpp.o
.PHONY : src/handlers/Internal.cpp.o

src/handlers/Internal.i: src/handlers/Internal.cpp.i

.PHONY : src/handlers/Internal.i

# target to preprocess a source file
src/handlers/Internal.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Internal.cpp.i
.PHONY : src/handlers/Internal.cpp.i

src/handlers/Internal.s: src/handlers/Internal.cpp.s

.PHONY : src/handlers/Internal.s

# target to generate assembly for a file
src/handlers/Internal.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Internal.cpp.s
.PHONY : src/handlers/Internal.cpp.s

src/handlers/Item.o: src/handlers/Item.cpp.o

.PHONY : src/handlers/Item.o

# target to build an object file
src/handlers/Item.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Item.cpp.o
.PHONY : src/handlers/Item.cpp.o

src/handlers/Item.i: src/handlers/Item.cpp.i

.PHONY : src/handlers/Item.i

# target to preprocess a source file
src/handlers/Item.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Item.cpp.i
.PHONY : src/handlers/Item.cpp.i

src/handlers/Item.s: src/handlers/Item.cpp.s

.PHONY : src/handlers/Item.s

# target to generate assembly for a file
src/handlers/Item.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Item.cpp.s
.PHONY : src/handlers/Item.cpp.s

src/handlers/Jukebox.o: src/handlers/Jukebox.cpp.o

.PHONY : src/handlers/Jukebox.o

# target to build an object file
src/handlers/Jukebox.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Jukebox.cpp.o
.PHONY : src/handlers/Jukebox.cpp.o

src/handlers/Jukebox.i: src/handlers/Jukebox.cpp.i

.PHONY : src/handlers/Jukebox.i

# target to preprocess a source file
src/handlers/Jukebox.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Jukebox.cpp.i
.PHONY : src/handlers/Jukebox.cpp.i

src/handlers/Jukebox.s: src/handlers/Jukebox.cpp.s

.PHONY : src/handlers/Jukebox.s

# target to generate assembly for a file
src/handlers/Jukebox.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Jukebox.cpp.s
.PHONY : src/handlers/Jukebox.cpp.s

src/handlers/Locker.o: src/handlers/Locker.cpp.o

.PHONY : src/handlers/Locker.o

# target to build an object file
src/handlers/Locker.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Locker.cpp.o
.PHONY : src/handlers/Locker.cpp.o

src/handlers/Locker.i: src/handlers/Locker.cpp.i

.PHONY : src/handlers/Locker.i

# target to preprocess a source file
src/handlers/Locker.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Locker.cpp.i
.PHONY : src/handlers/Locker.cpp.i

src/handlers/Locker.s: src/handlers/Locker.cpp.s

.PHONY : src/handlers/Locker.s

# target to generate assembly for a file
src/handlers/Locker.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Locker.cpp.s
.PHONY : src/handlers/Locker.cpp.s

src/handlers/Login.o: src/handlers/Login.cpp.o

.PHONY : src/handlers/Login.o

# target to build an object file
src/handlers/Login.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Login.cpp.o
.PHONY : src/handlers/Login.cpp.o

src/handlers/Login.i: src/handlers/Login.cpp.i

.PHONY : src/handlers/Login.i

# target to preprocess a source file
src/handlers/Login.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Login.cpp.i
.PHONY : src/handlers/Login.cpp.i

src/handlers/Login.s: src/handlers/Login.cpp.s

.PHONY : src/handlers/Login.s

# target to generate assembly for a file
src/handlers/Login.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Login.cpp.s
.PHONY : src/handlers/Login.cpp.s

src/handlers/Message.o: src/handlers/Message.cpp.o

.PHONY : src/handlers/Message.o

# target to build an object file
src/handlers/Message.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Message.cpp.o
.PHONY : src/handlers/Message.cpp.o

src/handlers/Message.i: src/handlers/Message.cpp.i

.PHONY : src/handlers/Message.i

# target to preprocess a source file
src/handlers/Message.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Message.cpp.i
.PHONY : src/handlers/Message.cpp.i

src/handlers/Message.s: src/handlers/Message.cpp.s

.PHONY : src/handlers/Message.s

# target to generate assembly for a file
src/handlers/Message.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Message.cpp.s
.PHONY : src/handlers/Message.cpp.s

src/handlers/Paperdoll.o: src/handlers/Paperdoll.cpp.o

.PHONY : src/handlers/Paperdoll.o

# target to build an object file
src/handlers/Paperdoll.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Paperdoll.cpp.o
.PHONY : src/handlers/Paperdoll.cpp.o

src/handlers/Paperdoll.i: src/handlers/Paperdoll.cpp.i

.PHONY : src/handlers/Paperdoll.i

# target to preprocess a source file
src/handlers/Paperdoll.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Paperdoll.cpp.i
.PHONY : src/handlers/Paperdoll.cpp.i

src/handlers/Paperdoll.s: src/handlers/Paperdoll.cpp.s

.PHONY : src/handlers/Paperdoll.s

# target to generate assembly for a file
src/handlers/Paperdoll.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Paperdoll.cpp.s
.PHONY : src/handlers/Paperdoll.cpp.s

src/handlers/Party.o: src/handlers/Party.cpp.o

.PHONY : src/handlers/Party.o

# target to build an object file
src/handlers/Party.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Party.cpp.o
.PHONY : src/handlers/Party.cpp.o

src/handlers/Party.i: src/handlers/Party.cpp.i

.PHONY : src/handlers/Party.i

# target to preprocess a source file
src/handlers/Party.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Party.cpp.i
.PHONY : src/handlers/Party.cpp.i

src/handlers/Party.s: src/handlers/Party.cpp.s

.PHONY : src/handlers/Party.s

# target to generate assembly for a file
src/handlers/Party.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Party.cpp.s
.PHONY : src/handlers/Party.cpp.s

src/handlers/Players.o: src/handlers/Players.cpp.o

.PHONY : src/handlers/Players.o

# target to build an object file
src/handlers/Players.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Players.cpp.o
.PHONY : src/handlers/Players.cpp.o

src/handlers/Players.i: src/handlers/Players.cpp.i

.PHONY : src/handlers/Players.i

# target to preprocess a source file
src/handlers/Players.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Players.cpp.i
.PHONY : src/handlers/Players.cpp.i

src/handlers/Players.s: src/handlers/Players.cpp.s

.PHONY : src/handlers/Players.s

# target to generate assembly for a file
src/handlers/Players.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Players.cpp.s
.PHONY : src/handlers/Players.cpp.s

src/handlers/Quest.o: src/handlers/Quest.cpp.o

.PHONY : src/handlers/Quest.o

# target to build an object file
src/handlers/Quest.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Quest.cpp.o
.PHONY : src/handlers/Quest.cpp.o

src/handlers/Quest.i: src/handlers/Quest.cpp.i

.PHONY : src/handlers/Quest.i

# target to preprocess a source file
src/handlers/Quest.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Quest.cpp.i
.PHONY : src/handlers/Quest.cpp.i

src/handlers/Quest.s: src/handlers/Quest.cpp.s

.PHONY : src/handlers/Quest.s

# target to generate assembly for a file
src/handlers/Quest.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Quest.cpp.s
.PHONY : src/handlers/Quest.cpp.s

src/handlers/Refresh.o: src/handlers/Refresh.cpp.o

.PHONY : src/handlers/Refresh.o

# target to build an object file
src/handlers/Refresh.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Refresh.cpp.o
.PHONY : src/handlers/Refresh.cpp.o

src/handlers/Refresh.i: src/handlers/Refresh.cpp.i

.PHONY : src/handlers/Refresh.i

# target to preprocess a source file
src/handlers/Refresh.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Refresh.cpp.i
.PHONY : src/handlers/Refresh.cpp.i

src/handlers/Refresh.s: src/handlers/Refresh.cpp.s

.PHONY : src/handlers/Refresh.s

# target to generate assembly for a file
src/handlers/Refresh.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Refresh.cpp.s
.PHONY : src/handlers/Refresh.cpp.s

src/handlers/Shop.o: src/handlers/Shop.cpp.o

.PHONY : src/handlers/Shop.o

# target to build an object file
src/handlers/Shop.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Shop.cpp.o
.PHONY : src/handlers/Shop.cpp.o

src/handlers/Shop.i: src/handlers/Shop.cpp.i

.PHONY : src/handlers/Shop.i

# target to preprocess a source file
src/handlers/Shop.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Shop.cpp.i
.PHONY : src/handlers/Shop.cpp.i

src/handlers/Shop.s: src/handlers/Shop.cpp.s

.PHONY : src/handlers/Shop.s

# target to generate assembly for a file
src/handlers/Shop.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Shop.cpp.s
.PHONY : src/handlers/Shop.cpp.s

src/handlers/Sit.o: src/handlers/Sit.cpp.o

.PHONY : src/handlers/Sit.o

# target to build an object file
src/handlers/Sit.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Sit.cpp.o
.PHONY : src/handlers/Sit.cpp.o

src/handlers/Sit.i: src/handlers/Sit.cpp.i

.PHONY : src/handlers/Sit.i

# target to preprocess a source file
src/handlers/Sit.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Sit.cpp.i
.PHONY : src/handlers/Sit.cpp.i

src/handlers/Sit.s: src/handlers/Sit.cpp.s

.PHONY : src/handlers/Sit.s

# target to generate assembly for a file
src/handlers/Sit.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Sit.cpp.s
.PHONY : src/handlers/Sit.cpp.s

src/handlers/Spell.o: src/handlers/Spell.cpp.o

.PHONY : src/handlers/Spell.o

# target to build an object file
src/handlers/Spell.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Spell.cpp.o
.PHONY : src/handlers/Spell.cpp.o

src/handlers/Spell.i: src/handlers/Spell.cpp.i

.PHONY : src/handlers/Spell.i

# target to preprocess a source file
src/handlers/Spell.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Spell.cpp.i
.PHONY : src/handlers/Spell.cpp.i

src/handlers/Spell.s: src/handlers/Spell.cpp.s

.PHONY : src/handlers/Spell.s

# target to generate assembly for a file
src/handlers/Spell.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Spell.cpp.s
.PHONY : src/handlers/Spell.cpp.s

src/handlers/StatSkill.o: src/handlers/StatSkill.cpp.o

.PHONY : src/handlers/StatSkill.o

# target to build an object file
src/handlers/StatSkill.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/StatSkill.cpp.o
.PHONY : src/handlers/StatSkill.cpp.o

src/handlers/StatSkill.i: src/handlers/StatSkill.cpp.i

.PHONY : src/handlers/StatSkill.i

# target to preprocess a source file
src/handlers/StatSkill.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/StatSkill.cpp.i
.PHONY : src/handlers/StatSkill.cpp.i

src/handlers/StatSkill.s: src/handlers/StatSkill.cpp.s

.PHONY : src/handlers/StatSkill.s

# target to generate assembly for a file
src/handlers/StatSkill.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/StatSkill.cpp.s
.PHONY : src/handlers/StatSkill.cpp.s

src/handlers/Talk.o: src/handlers/Talk.cpp.o

.PHONY : src/handlers/Talk.o

# target to build an object file
src/handlers/Talk.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Talk.cpp.o
.PHONY : src/handlers/Talk.cpp.o

src/handlers/Talk.i: src/handlers/Talk.cpp.i

.PHONY : src/handlers/Talk.i

# target to preprocess a source file
src/handlers/Talk.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Talk.cpp.i
.PHONY : src/handlers/Talk.cpp.i

src/handlers/Talk.s: src/handlers/Talk.cpp.s

.PHONY : src/handlers/Talk.s

# target to generate assembly for a file
src/handlers/Talk.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Talk.cpp.s
.PHONY : src/handlers/Talk.cpp.s

src/handlers/Trade.o: src/handlers/Trade.cpp.o

.PHONY : src/handlers/Trade.o

# target to build an object file
src/handlers/Trade.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Trade.cpp.o
.PHONY : src/handlers/Trade.cpp.o

src/handlers/Trade.i: src/handlers/Trade.cpp.i

.PHONY : src/handlers/Trade.i

# target to preprocess a source file
src/handlers/Trade.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Trade.cpp.i
.PHONY : src/handlers/Trade.cpp.i

src/handlers/Trade.s: src/handlers/Trade.cpp.s

.PHONY : src/handlers/Trade.s

# target to generate assembly for a file
src/handlers/Trade.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Trade.cpp.s
.PHONY : src/handlers/Trade.cpp.s

src/handlers/Walk.o: src/handlers/Walk.cpp.o

.PHONY : src/handlers/Walk.o

# target to build an object file
src/handlers/Walk.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Walk.cpp.o
.PHONY : src/handlers/Walk.cpp.o

src/handlers/Walk.i: src/handlers/Walk.cpp.i

.PHONY : src/handlers/Walk.i

# target to preprocess a source file
src/handlers/Walk.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Walk.cpp.i
.PHONY : src/handlers/Walk.cpp.i

src/handlers/Walk.s: src/handlers/Walk.cpp.s

.PHONY : src/handlers/Walk.s

# target to generate assembly for a file
src/handlers/Walk.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Walk.cpp.s
.PHONY : src/handlers/Walk.cpp.s

src/handlers/Warp.o: src/handlers/Warp.cpp.o

.PHONY : src/handlers/Warp.o

# target to build an object file
src/handlers/Warp.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Warp.cpp.o
.PHONY : src/handlers/Warp.cpp.o

src/handlers/Warp.i: src/handlers/Warp.cpp.i

.PHONY : src/handlers/Warp.i

# target to preprocess a source file
src/handlers/Warp.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Warp.cpp.i
.PHONY : src/handlers/Warp.cpp.i

src/handlers/Warp.s: src/handlers/Warp.cpp.s

.PHONY : src/handlers/Warp.s

# target to generate assembly for a file
src/handlers/Warp.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Warp.cpp.s
.PHONY : src/handlers/Warp.cpp.s

src/handlers/Welcome.o: src/handlers/Welcome.cpp.o

.PHONY : src/handlers/Welcome.o

# target to build an object file
src/handlers/Welcome.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Welcome.cpp.o
.PHONY : src/handlers/Welcome.cpp.o

src/handlers/Welcome.i: src/handlers/Welcome.cpp.i

.PHONY : src/handlers/Welcome.i

# target to preprocess a source file
src/handlers/Welcome.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Welcome.cpp.i
.PHONY : src/handlers/Welcome.cpp.i

src/handlers/Welcome.s: src/handlers/Welcome.cpp.s

.PHONY : src/handlers/Welcome.s

# target to generate assembly for a file
src/handlers/Welcome.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/Welcome.cpp.s
.PHONY : src/handlers/Welcome.cpp.s

src/handlers/handlers.o: src/handlers/handlers.cpp.o

.PHONY : src/handlers/handlers.o

# target to build an object file
src/handlers/handlers.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/handlers.cpp.o
.PHONY : src/handlers/handlers.cpp.o

src/handlers/handlers.i: src/handlers/handlers.cpp.i

.PHONY : src/handlers/handlers.i

# target to preprocess a source file
src/handlers/handlers.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/handlers.cpp.i
.PHONY : src/handlers/handlers.cpp.i

src/handlers/handlers.s: src/handlers/handlers.cpp.s

.PHONY : src/handlers/handlers.s

# target to generate assembly for a file
src/handlers/handlers.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/handlers/handlers.cpp.s
.PHONY : src/handlers/handlers.cpp.s

src/hash.o: src/hash.cpp.o

.PHONY : src/hash.o

# target to build an object file
src/hash.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/hash.cpp.o
.PHONY : src/hash.cpp.o

src/hash.i: src/hash.cpp.i

.PHONY : src/hash.i

# target to preprocess a source file
src/hash.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/hash.cpp.i
.PHONY : src/hash.cpp.i

src/hash.s: src/hash.cpp.s

.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/hash.cpp.s
.PHONY : src/hash.cpp.s

src/i18n.o: src/i18n.cpp.o

.PHONY : src/i18n.o

# target to build an object file
src/i18n.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/i18n.cpp.o
.PHONY : src/i18n.cpp.o

src/i18n.i: src/i18n.cpp.i

.PHONY : src/i18n.i

# target to preprocess a source file
src/i18n.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/i18n.cpp.i
.PHONY : src/i18n.cpp.i

src/i18n.s: src/i18n.cpp.s

.PHONY : src/i18n.s

# target to generate assembly for a file
src/i18n.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/i18n.cpp.s
.PHONY : src/i18n.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map.o: src/map.cpp.o

.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/nanohttp.o: src/nanohttp.cpp.o

.PHONY : src/nanohttp.o

# target to build an object file
src/nanohttp.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/nanohttp.cpp.o
.PHONY : src/nanohttp.cpp.o

src/nanohttp.i: src/nanohttp.cpp.i

.PHONY : src/nanohttp.i

# target to preprocess a source file
src/nanohttp.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/nanohttp.cpp.i
.PHONY : src/nanohttp.cpp.i

src/nanohttp.s: src/nanohttp.cpp.s

.PHONY : src/nanohttp.s

# target to generate assembly for a file
src/nanohttp.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/nanohttp.cpp.s
.PHONY : src/nanohttp.cpp.s

src/npc.o: src/npc.cpp.o

.PHONY : src/npc.o

# target to build an object file
src/npc.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/npc.cpp.o
.PHONY : src/npc.cpp.o

src/npc.i: src/npc.cpp.i

.PHONY : src/npc.i

# target to preprocess a source file
src/npc.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/npc.cpp.i
.PHONY : src/npc.cpp.i

src/npc.s: src/npc.cpp.s

.PHONY : src/npc.s

# target to generate assembly for a file
src/npc.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/npc.cpp.s
.PHONY : src/npc.cpp.s

src/npc_data.o: src/npc_data.cpp.o

.PHONY : src/npc_data.o

# target to build an object file
src/npc_data.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/npc_data.cpp.o
.PHONY : src/npc_data.cpp.o

src/npc_data.i: src/npc_data.cpp.i

.PHONY : src/npc_data.i

# target to preprocess a source file
src/npc_data.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/npc_data.cpp.i
.PHONY : src/npc_data.cpp.i

src/npc_data.s: src/npc_data.cpp.s

.PHONY : src/npc_data.s

# target to generate assembly for a file
src/npc_data.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/npc_data.cpp.s
.PHONY : src/npc_data.cpp.s

src/packet.o: src/packet.cpp.o

.PHONY : src/packet.o

# target to build an object file
src/packet.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/packet.cpp.o
.PHONY : src/packet.cpp.o

src/packet.i: src/packet.cpp.i

.PHONY : src/packet.i

# target to preprocess a source file
src/packet.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/packet.cpp.i
.PHONY : src/packet.cpp.i

src/packet.s: src/packet.cpp.s

.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/packet.cpp.s
.PHONY : src/packet.cpp.s

src/party.o: src/party.cpp.o

.PHONY : src/party.o

# target to build an object file
src/party.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/party.cpp.o
.PHONY : src/party.cpp.o

src/party.i: src/party.cpp.i

.PHONY : src/party.i

# target to preprocess a source file
src/party.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/party.cpp.i
.PHONY : src/party.cpp.i

src/party.s: src/party.cpp.s

.PHONY : src/party.s

# target to generate assembly for a file
src/party.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/party.cpp.s
.PHONY : src/party.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/quest.o: src/quest.cpp.o

.PHONY : src/quest.o

# target to build an object file
src/quest.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/quest.cpp.o
.PHONY : src/quest.cpp.o

src/quest.i: src/quest.cpp.i

.PHONY : src/quest.i

# target to preprocess a source file
src/quest.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/quest.cpp.i
.PHONY : src/quest.cpp.i

src/quest.s: src/quest.cpp.s

.PHONY : src/quest.s

# target to generate assembly for a file
src/quest.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/quest.cpp.s
.PHONY : src/quest.cpp.s

src/sha256.o: src/sha256.c.o

.PHONY : src/sha256.o

# target to build an object file
src/sha256.c.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/sha256.c.o
.PHONY : src/sha256.c.o

src/sha256.i: src/sha256.c.i

.PHONY : src/sha256.i

# target to preprocess a source file
src/sha256.c.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/sha256.c.i
.PHONY : src/sha256.c.i

src/sha256.s: src/sha256.c.s

.PHONY : src/sha256.s

# target to generate assembly for a file
src/sha256.c.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/sha256.c.s
.PHONY : src/sha256.c.s

src/sln.o: src/sln.cpp.o

.PHONY : src/sln.o

# target to build an object file
src/sln.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/sln.cpp.o
.PHONY : src/sln.cpp.o

src/sln.i: src/sln.cpp.i

.PHONY : src/sln.i

# target to preprocess a source file
src/sln.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/sln.cpp.i
.PHONY : src/sln.cpp.i

src/sln.s: src/sln.cpp.s

.PHONY : src/sln.s

# target to generate assembly for a file
src/sln.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/sln.cpp.s
.PHONY : src/sln.cpp.s

src/socket.o: src/socket.cpp.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/socket.cpp.o
.PHONY : src/socket.cpp.o

src/socket.i: src/socket.cpp.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/socket.cpp.i
.PHONY : src/socket.cpp.i

src/socket.s: src/socket.cpp.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/socket.cpp.s
.PHONY : src/socket.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/util/rpn.o: src/util/rpn.cpp.o

.PHONY : src/util/rpn.o

# target to build an object file
src/util/rpn.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/rpn.cpp.o
.PHONY : src/util/rpn.cpp.o

src/util/rpn.i: src/util/rpn.cpp.i

.PHONY : src/util/rpn.i

# target to preprocess a source file
src/util/rpn.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/rpn.cpp.i
.PHONY : src/util/rpn.cpp.i

src/util/rpn.s: src/util/rpn.cpp.s

.PHONY : src/util/rpn.s

# target to generate assembly for a file
src/util/rpn.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/rpn.cpp.s
.PHONY : src/util/rpn.cpp.s

src/util/rpn_lex.o: src/util/rpn_lex.cpp.o

.PHONY : src/util/rpn_lex.o

# target to build an object file
src/util/rpn_lex.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/rpn_lex.cpp.o
.PHONY : src/util/rpn_lex.cpp.o

src/util/rpn_lex.i: src/util/rpn_lex.cpp.i

.PHONY : src/util/rpn_lex.i

# target to preprocess a source file
src/util/rpn_lex.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/rpn_lex.cpp.i
.PHONY : src/util/rpn_lex.cpp.i

src/util/rpn_lex.s: src/util/rpn_lex.cpp.s

.PHONY : src/util/rpn_lex.s

# target to generate assembly for a file
src/util/rpn_lex.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/rpn_lex.cpp.s
.PHONY : src/util/rpn_lex.cpp.s

src/util/variant.o: src/util/variant.cpp.o

.PHONY : src/util/variant.o

# target to build an object file
src/util/variant.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/variant.cpp.o
.PHONY : src/util/variant.cpp.o

src/util/variant.i: src/util/variant.cpp.i

.PHONY : src/util/variant.i

# target to preprocess a source file
src/util/variant.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/variant.cpp.i
.PHONY : src/util/variant.cpp.i

src/util/variant.s: src/util/variant.cpp.s

.PHONY : src/util/variant.s

# target to generate assembly for a file
src/util/variant.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/util/variant.cpp.s
.PHONY : src/util/variant.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/eoserv.dir/build.make CMakeFiles/eoserv.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... eoserv"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... src/arena.o"
	@echo "... src/arena.i"
	@echo "... src/arena.s"
	@echo "... src/character.o"
	@echo "... src/character.i"
	@echo "... src/character.s"
	@echo "... src/command_source.o"
	@echo "... src/command_source.i"
	@echo "... src/command_source.s"
	@echo "... src/commands/admin.o"
	@echo "... src/commands/admin.i"
	@echo "... src/commands/admin.s"
	@echo "... src/commands/char_mod.o"
	@echo "... src/commands/char_mod.i"
	@echo "... src/commands/char_mod.s"
	@echo "... src/commands/commands.o"
	@echo "... src/commands/commands.i"
	@echo "... src/commands/commands.s"
	@echo "... src/commands/debug.o"
	@echo "... src/commands/debug.i"
	@echo "... src/commands/debug.s"
	@echo "... src/commands/general.o"
	@echo "... src/commands/general.i"
	@echo "... src/commands/general.s"
	@echo "... src/commands/info.o"
	@echo "... src/commands/info.i"
	@echo "... src/commands/info.s"
	@echo "... src/commands/map.o"
	@echo "... src/commands/map.i"
	@echo "... src/commands/map.s"
	@echo "... src/commands/moderation.o"
	@echo "... src/commands/moderation.i"
	@echo "... src/commands/moderation.s"
	@echo "... src/commands/player.o"
	@echo "... src/commands/player.i"
	@echo "... src/commands/player.s"
	@echo "... src/commands/server.o"
	@echo "... src/commands/server.i"
	@echo "... src/commands/server.s"
	@echo "... src/commands/warp.o"
	@echo "... src/commands/warp.i"
	@echo "... src/commands/warp.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/console.o"
	@echo "... src/console.i"
	@echo "... src/console.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/dialog.o"
	@echo "... src/dialog.i"
	@echo "... src/dialog.s"
	@echo "... src/eoclient.o"
	@echo "... src/eoclient.i"
	@echo "... src/eoclient.s"
	@echo "... src/eodata.o"
	@echo "... src/eodata.i"
	@echo "... src/eodata.s"
	@echo "... src/eoplus.o"
	@echo "... src/eoplus.i"
	@echo "... src/eoplus.s"
	@echo "... src/eoplus/context.o"
	@echo "... src/eoplus/context.i"
	@echo "... src/eoplus/context.s"
	@echo "... src/eoplus/lex.o"
	@echo "... src/eoplus/lex.i"
	@echo "... src/eoplus/lex.s"
	@echo "... src/eoplus/parse.o"
	@echo "... src/eoplus/parse.i"
	@echo "... src/eoplus/parse.s"
	@echo "... src/eoserv_config.o"
	@echo "... src/eoserv_config.i"
	@echo "... src/eoserv_config.s"
	@echo "... src/eoserver.o"
	@echo "... src/eoserver.i"
	@echo "... src/eoserver.s"
	@echo "... src/extra/seose_compat.o"
	@echo "... src/extra/seose_compat.i"
	@echo "... src/extra/seose_compat.s"
	@echo "... src/guild.o"
	@echo "... src/guild.i"
	@echo "... src/guild.s"
	@echo "... src/handlers/Account.o"
	@echo "... src/handlers/Account.i"
	@echo "... src/handlers/Account.s"
	@echo "... src/handlers/AdminInteract.o"
	@echo "... src/handlers/AdminInteract.i"
	@echo "... src/handlers/AdminInteract.s"
	@echo "... src/handlers/Attack.o"
	@echo "... src/handlers/Attack.i"
	@echo "... src/handlers/Attack.s"
	@echo "... src/handlers/Bank.o"
	@echo "... src/handlers/Bank.i"
	@echo "... src/handlers/Bank.s"
	@echo "... src/handlers/Barber.o"
	@echo "... src/handlers/Barber.i"
	@echo "... src/handlers/Barber.s"
	@echo "... src/handlers/Board.o"
	@echo "... src/handlers/Board.i"
	@echo "... src/handlers/Board.s"
	@echo "... src/handlers/Book.o"
	@echo "... src/handlers/Book.i"
	@echo "... src/handlers/Book.s"
	@echo "... src/handlers/Chair.o"
	@echo "... src/handlers/Chair.i"
	@echo "... src/handlers/Chair.s"
	@echo "... src/handlers/Character.o"
	@echo "... src/handlers/Character.i"
	@echo "... src/handlers/Character.s"
	@echo "... src/handlers/Chest.o"
	@echo "... src/handlers/Chest.i"
	@echo "... src/handlers/Chest.s"
	@echo "... src/handlers/Citizen.o"
	@echo "... src/handlers/Citizen.i"
	@echo "... src/handlers/Citizen.s"
	@echo "... src/handlers/Connection.o"
	@echo "... src/handlers/Connection.i"
	@echo "... src/handlers/Connection.s"
	@echo "... src/handlers/Door.o"
	@echo "... src/handlers/Door.i"
	@echo "... src/handlers/Door.s"
	@echo "... src/handlers/Emote.o"
	@echo "... src/handlers/Emote.i"
	@echo "... src/handlers/Emote.s"
	@echo "... src/handlers/Face.o"
	@echo "... src/handlers/Face.i"
	@echo "... src/handlers/Face.s"
	@echo "... src/handlers/Global.o"
	@echo "... src/handlers/Global.i"
	@echo "... src/handlers/Global.s"
	@echo "... src/handlers/Guild.o"
	@echo "... src/handlers/Guild.i"
	@echo "... src/handlers/Guild.s"
	@echo "... src/handlers/Init.o"
	@echo "... src/handlers/Init.i"
	@echo "... src/handlers/Init.s"
	@echo "... src/handlers/Internal.o"
	@echo "... src/handlers/Internal.i"
	@echo "... src/handlers/Internal.s"
	@echo "... src/handlers/Item.o"
	@echo "... src/handlers/Item.i"
	@echo "... src/handlers/Item.s"
	@echo "... src/handlers/Jukebox.o"
	@echo "... src/handlers/Jukebox.i"
	@echo "... src/handlers/Jukebox.s"
	@echo "... src/handlers/Locker.o"
	@echo "... src/handlers/Locker.i"
	@echo "... src/handlers/Locker.s"
	@echo "... src/handlers/Login.o"
	@echo "... src/handlers/Login.i"
	@echo "... src/handlers/Login.s"
	@echo "... src/handlers/Message.o"
	@echo "... src/handlers/Message.i"
	@echo "... src/handlers/Message.s"
	@echo "... src/handlers/Paperdoll.o"
	@echo "... src/handlers/Paperdoll.i"
	@echo "... src/handlers/Paperdoll.s"
	@echo "... src/handlers/Party.o"
	@echo "... src/handlers/Party.i"
	@echo "... src/handlers/Party.s"
	@echo "... src/handlers/Players.o"
	@echo "... src/handlers/Players.i"
	@echo "... src/handlers/Players.s"
	@echo "... src/handlers/Quest.o"
	@echo "... src/handlers/Quest.i"
	@echo "... src/handlers/Quest.s"
	@echo "... src/handlers/Refresh.o"
	@echo "... src/handlers/Refresh.i"
	@echo "... src/handlers/Refresh.s"
	@echo "... src/handlers/Shop.o"
	@echo "... src/handlers/Shop.i"
	@echo "... src/handlers/Shop.s"
	@echo "... src/handlers/Sit.o"
	@echo "... src/handlers/Sit.i"
	@echo "... src/handlers/Sit.s"
	@echo "... src/handlers/Spell.o"
	@echo "... src/handlers/Spell.i"
	@echo "... src/handlers/Spell.s"
	@echo "... src/handlers/StatSkill.o"
	@echo "... src/handlers/StatSkill.i"
	@echo "... src/handlers/StatSkill.s"
	@echo "... src/handlers/Talk.o"
	@echo "... src/handlers/Talk.i"
	@echo "... src/handlers/Talk.s"
	@echo "... src/handlers/Trade.o"
	@echo "... src/handlers/Trade.i"
	@echo "... src/handlers/Trade.s"
	@echo "... src/handlers/Walk.o"
	@echo "... src/handlers/Walk.i"
	@echo "... src/handlers/Walk.s"
	@echo "... src/handlers/Warp.o"
	@echo "... src/handlers/Warp.i"
	@echo "... src/handlers/Warp.s"
	@echo "... src/handlers/Welcome.o"
	@echo "... src/handlers/Welcome.i"
	@echo "... src/handlers/Welcome.s"
	@echo "... src/handlers/handlers.o"
	@echo "... src/handlers/handlers.i"
	@echo "... src/handlers/handlers.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/i18n.o"
	@echo "... src/i18n.i"
	@echo "... src/i18n.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/nanohttp.o"
	@echo "... src/nanohttp.i"
	@echo "... src/nanohttp.s"
	@echo "... src/npc.o"
	@echo "... src/npc.i"
	@echo "... src/npc.s"
	@echo "... src/npc_data.o"
	@echo "... src/npc_data.i"
	@echo "... src/npc_data.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/party.o"
	@echo "... src/party.i"
	@echo "... src/party.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/quest.o"
	@echo "... src/quest.i"
	@echo "... src/quest.s"
	@echo "... src/sha256.o"
	@echo "... src/sha256.i"
	@echo "... src/sha256.s"
	@echo "... src/sln.o"
	@echo "... src/sln.i"
	@echo "... src/sln.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/util/rpn.o"
	@echo "... src/util/rpn.i"
	@echo "... src/util/rpn.s"
	@echo "... src/util/rpn_lex.o"
	@echo "... src/util/rpn_lex.i"
	@echo "... src/util/rpn_lex.s"
	@echo "... src/util/variant.o"
	@echo "... src/util/variant.i"
	@echo "... src/util/variant.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

